### PR TITLE
added mars

### PR DESCRIPTION
**Pull request by abhijeet-chatterjee**

### CODE REVIEW

**Comment by naman-gupta99** [comment]
This looks good. But there is a small issue that needs fixing. So whenever the planet goes out of the screen the page length gets increased. We need to limit the screen scroll to just one page. Similarly, on a mobile phone screen this will also lead to issues in the horizontal axis.

**Review by naman-gupta99 — CHANGES_REQUESTED** [review]
Try fixing the scroll issue.

**Comment by abhijeet-chatterjee** [comment]
Should be decrease the basic zoom during load ?

**Comment by naman-gupta99** [comment]
> Should be decrease the basic zoom during load ?

But that would feel a bit underwhelming. It would be better if we just lock the scroll to place.

**Comment by naman-gupta99** [comment]
If you want I can merge this PR and create a new issue with this.

**Comment by abhijeet-chatterjee** [comment]
> If you want I can merge this PR and create a new issue with this.

That would be great

**Comment by abhijeet-chatterjee** [comment]
> > Should be decrease the basic zoom during load ?
> 
> But that would feel a bit underwhelming. It would be better if we just lock the scroll to place.

If we do just that some planets may out of bound for some time during revolution

**Pull request merged**
