### PR TITLE
added stars background

### PR DESCRIPTION
**Pull request by abhijeet-chatterjee**
Realted to #4

### CODE REVIEW

**Comment by naman-gupta99** [comment]
Can you please try some other image. This one gets blurred on larger screens. Try using a svg element.

**Comment by abhijeet-chatterjee** [comment]
@naman-gupta99 Can you review now ?

**Comment by naman-gupta99** [comment]
Hey! This is okay. Although I would still like that you try and find an svg element for this.
Try to look for something like this and include it in the html as an svg.

Try following the below two links and they would guide you how you can do this in a good way.

https://freesvg.org/night-sky
https://stackoverflow.com/questions/9185434/using-svg-as-background-image

**Review by naman-gupta99 — CHANGES_REQUESTED** [review]
Change the image to a SVG

**Pull request merged**
